version: '3.7'

services:

  # Mainflux services
  users:
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.users.loadbalancer.server.port=8180
        - traefik.http.routers.users.rule=HostRegexp(`{subdomain:users}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.users.entrypoints=http

  things:
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.things.loadbalancer.server.port=8182
        - traefik.http.routers.things.rule=HostRegexp(`{subdomain:things}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.things.entrypoints=http

  authn:
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.authn.loadbalancer.server.port=8183
        - traefik.http.routers.authn.rule=HostRegexp(`{subdomain:authn}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.authn.entrypoints=http

  # KNoT Fog Core
  storage:
    volumes:
      - ../knot-cloud-storage:/usr/src/app
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.storage.loadbalancer.server.port=8181
        - traefik.http.routers.storage.rule=HostRegexp(`{subdomain:storage}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.storage.entrypoints=http

  babeltower:
    volumes:
      - ../knot-babeltower:/usr/src/app
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.babeltower.loadbalancer.server.port=8080
        - traefik.http.routers.babeltower.rule=HostRegexp(`{subdomain:api}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.babeltower.entrypoints=http

  # External dependencies: database, tracing, message broker, load balancer.
  things-redis:
    image: redis:5.0-alpine
    deploy:
      resources:
        limits:
          memory: 300M

  es-redis:
    image: redis:5.0-alpine
    deploy:
      resources:
        limits:
          memory: 300M

  things-db:
    image: postgres:9.6.17-alpine
    env_file: './env.d/mainflux-things.env'

  users-db:
    image: postgres:9.6.17-alpine
    env_file: './env.d/mainflux-users.env'

  authn-db:
    image: postgres:9.6.17-alpine
    env_file: './env.d/mainflux-authn.env'

  rabbitmq:
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        # Management dashboard configuration
        - traefik.http.services.rabbitmq-admin.loadbalancer.server.port=15672
        - traefik.http.routers.rabbitmq-admin.rule=HostRegexp(`{subdomain:admin}.{domain:[a-zA-Z0-9.]+}`)
        - traefik.http.routers.rabbitmq-admin.entrypoints=management
        # AMQP configuration
        - traefik.tcp.services.rabbitmq.loadbalancer.server.port=5672
        - traefik.tcp.routers.rabbitmq.rule=HostSNI(`*`)
        - traefik.tcp.routers.rabbitmq.entrypoints=broker

  jaeger:
    deploy:
      replicas: 1

volumes:
  mainflux-things-db-volume:
  mainflux-users-db-volume:
  mainflux-authn-db-volume:
  knot-cloud-db-volume:
